### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by mewmew** [xh3b4sd/anna#178]
Hi Tim,

From the looks of it, Anna seems like a very interesting project. After reading the [License section](https://github.com/xh3b4sd/anna#license) of the readme, and reviewing the contents of the [LICENSE file](https://github.com/xh3b4sd/anna/blob/master/LICENSE), I still feel uncertain about which license is covering this project.

To further clarrify, is the project goverend by an [OSI approved license](https://opensource.org/licenses)?

Thanks for releasing this project into the wild. I hope it may have an exciting future!

Cheers /u

**Comment by xh3b4sd** [comment]
Hey there. Sorry for being late. I did not get any notification about the issues you created. I watched the project now and hope in the future this will work out more nicely. Anyway, I am not that license guy. My idea was to have the copyright of this piece of intellectual property. Anybody should be able to make use of it to serve mankind. As far as this is possible I would only like to have a stake in this then. Means, still working on the project to drive it even more forward. What do you think would make sense here to improve on the license file?

**Comment by mewmew** [comment]
> Hey there. Sorry for being late. I did not get any notification about the issues you created. I watched the project now and hope in the future this will work out more nicely. Anyway, I am not that license guy. My idea was to have the copyright of this piece of intellectual property. Anybody should be able to make use of it to serve mankind. As far as this is possible I would only like to have a stake in this then. Means, still working on the project to drive it even more forward. What do you think would make sense here to improve on the license file?

Definitely makes sense. I'm not a license guy myself, but know that for people to get involved in project, unfortunately this day and age requires a lot of legal overhead. Personally I release all of my code into the [public domain](https://creativecommons.org/publicdomain/zero/1.0/), but if you wish to retain your copyright I would recommend using the same license as the Go project, which is a [3-clause BSD license](https://golang.org/LICENSE). Or, as some projects wish to do, use a [2-clause BSD license](https://opensource.org/licenses/BSD-2-Clause).

Hopefully, in the feature there will be no need for a license, but sharing information, culture and knowledge is deeply engrained in the society that it goes without saying.

**Comment by mewmew** [comment]
You may also consider a [Zlib license](https://opensource.org/licenses/Zlib) or an [MIT license](https://opensource.org/licenses/MIT), both of which are roughly equivalent to the BSD license.

There are of cause a lot of options, and you may review the list at https://opensource.org/licenses/category in your own time.

I really wish the future arrives sooner rather than later, where the requirement to use a license simply to spread ideas is a thing of the past.

**Comment by mewmew** [comment]
Just to be clear, I've mainly highlighted [permissive licensed](https://en.wikipedia.org/wiki/Permissive_software_licence) which grant users of the software rights to use, modify and redistribute the software without so many restrictions, simply because these licensing models lay closer to my heart. Other licensing models exist, such as those encouraged by the [Copyleft movement](https://en.wikipedia.org/wiki/Copyleft). Rather than presenting you with my view on the topic, I'd better let you make up your own opinion :)
