### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by mewmew** [xh3b4sd/anna#180]
I really like that you've taken your time to write down inspiring thoughts and ideas in a chronological order within the diary of the project. It really helps getting a deeper understanding of the design decisions taken along the way.

While reading through some of the diary entires, I noticed that a few links have become stale and now result in 404 errors. To identify the pages containing broken links I wrote a [small crawler script](https://gist.github.com/mewmew/57196a0281f48ff83c5d78397f1ae73e) which automates the task.

Currently it has identified the following broken links:

* [x] NOT FOUND: http://github.com/xh3b4sd/anna/.github/CONTRIBUTING.md (from http://github.com/xh3b4sd/anna/blob/master/.github/PULL_REQUEST_TEMPLATE.md)
* [x] NOT FOUND: http://github.com/xh3b4sd/anna/blob/master/.github.com/CONTRIBUTING.md (from http://github.com/xh3b4sd/anna/blob/master/README.md)
* [x] NOT FOUND: http://github.com/xh3b4sd/anna/blob/master/.github.com/CONTRIBUTING.md (from http://github.com/xh3b4sd/anna/tree/master)
* [x] NOT FOUND: http://github.com/xh3b4sd/anna/blob/master/doc/challenge/guidance.md (from http://github.com/xh3b4sd/anna/blob/master/doc/evaluation/starting_a_conversation_by_greeting.md)
* [x] NOT FOUND: http://github.com/xh3b4sd/anna/blob/master/doc/concept/core.md (from http://github.com/xh3b4sd/anna/blob/master/doc/diary/2016_01_18.md)
* ~~NOT FOUND: http://github.com/xh3b4sd/anna/blob/master/doc/concept/data_structure.md (from http://github.com/xh3b4sd/anna/blob/master/doc/concept/README.md)~~ (there was never real data structure documentation in this file)
* ~~NOT FOUND: http://github.com/xh3b4sd/anna/blob/master/doc/concept/data_structure.md (from http://github.com/xh3b4sd/anna/tree/master/doc/concept)~~ (there was never real data structure documentation in this file)
* [x] NOT FOUND: http://github.com/xh3b4sd/anna/blob/master/doc/concept/factory.md (from http://github.com/xh3b4sd/anna/blob/master/doc/diary/2016_02_01.md)
* [x] NOT FOUND: http://github.com/xh3b4sd/anna/blob/master/doc/concept/stage.md (from http://github.com/xh3b4sd/anna/blob/master/doc/diary/2016_06_23.md)
* [x] NOT FOUND: http://github.com/xh3b4sd/anna/blob/master/doc/concept/state.md (from http://github.com/xh3b4sd/anna/blob/master/doc/concept/network.md)
* ~~NOT FOUND: http://github.com/xh3b4sd/anna/blob/master/doc/concept/strategy.md (from http://github.com/xh3b4sd/anna/blob/master/doc/concept/clg.md)~~ (I removed the link from the docs because it does not make sense anymore within the current design.)
* ~~NOT FOUND: http://github.com/xh3b4sd/anna/blob/master/doc/concept/strategy.md (from http://github.com/xh3b4sd/anna/blob/master/doc/concept/impulse.md)~~ (The concept of an impulse itself was just removed within the last PR #173.)
* ~~NOT FOUND: http://github.com/xh3b4sd/anna/blob/master/doc/concept/strategy.md (from http://github.com/xh3b4sd/anna/blob/master/doc/concept/input.md)~~ (I removed the link from the docs because it does not make sense anymore within the current design.)
* [x] NOT FOUND: http://github.com/xh3b4sd/anna/blob/master/doc/concept/strategy.md (from http://github.com/xh3b4sd/anna/blob/master/doc/diary/2016_06_23.md)
* [x] NOT FOUND: http://github.com/xh3b4sd/anna/blob/master/doc/diary/17_01_2016.md (from http://github.com/xh3b4sd/anna/blob/master/doc/diary/2016_01_18.md)
* [x] NOT FOUND: http://github.com/xh3b4sd/anna/blob/master/doc/diary/doc (from http://github.com/xh3b4sd/anna/blob/master/doc/diary/2016_01_11.md)
* ~~NOT FOUND: http://godoc.org/github.com/xh3b4sd/anna/net/pat (from http://github.com/xh3b4sd/anna/blob/master/doc/diary/2016_03_22.md)~~ (the go source code for this package was removed)
* ~~NOT FOUND: http://godoc.org/github.com/xh3b4sd/anna/net/pat (from http://github.com/xh3b4sd/anna/blob/master/doc/roadmap/README.md)~~ (the go source code for this package was removed)
* NOT FOUND: http://godoc.org/github.com/xh3b4sd/anna/net/pat (from http://github.com/xh3b4sd/anna/tree/master/doc/roadmap)~~ (the go source code for this package was removed)
* ~~NOT FOUND: http://godoc.org/github.com/xh3b4sd/anna/state (from http://github.com/xh3b4sd/anna/blob/master/doc/diary/2016_02_01.md)~~ (the go source code for this package was removed)
* ~~GET ERROR; Get http://anna.local: dial tcp: lookup anna.local: no such host (from http://github.com/xh3b4sd/anna/blob/master/doc/diary/2016_05_16.md)~~ (You need to run the local environment to make it available under http://anna.local. See the WIP here https://github.com/xh3b4sd/anna.local)
* ~~GET ERROR; Get http://www.kfki.hu~csdori/Concepts.pdf: dial tcp: lookup www.kfki.hu~csdori: invalid domain name (from http://github.com/xh3b4sd/anna/blob/master/doc/diary/2016_04_06.md)~~ (the remote source is gone)

**Comment by mewmew** [comment]
Reviewing the list, it seems like #179 failed to address the broken link in the PR template. It should have been `https://github.com/xh3b4sd/anna/blob/master/.github/CONTRIBUTING.md` rather than `https://github.com/xh3b4sd/anna/.github/CONTRIBUTING.md`. Sorry for the premature PR.

**Comment by xh3b4sd** [comment]
Thanks for your efforts and kind words. In hindsight I have done a bad job referencing pages within the project. There is a nice trick you can make use of to get the proper URL of the current Github page. Simply hit `y`. I should make use of it. The pages missing in godoc are gone as soon as the code changes or whole packages have been removed. This still happens from time to time like in the recent PR #173. I am still in a heavy conceptual phase and thus the code is more or less volatile. I try to change this in time. At some point the code is getting more mature I hope. 

I can try to address the broken links where possible.

**Comment by mewmew** [comment]
> I am still in a heavy conceptual phase and thus the code is more or less volatile. I try to change this in time. At some point the code is getting more mature I hope.

No worries at all. I am thrilled to see the evolution of this project, and personally love the fact that it is in a conceptual think tank stage of development where ideas are tested, rejected and refined organically.

Keep brainstoriming, and don't feel pressured to find a stable API just yet. It feels like too many projects get stuck in local optimum because of this, and this is why I'd love to see where projects such as these may go in a couple of years.
